import { defineField, defineType } from 'sanity';

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'הגדרות אתר',
  type: 'document',
  groups: [
    { name: 'business', title: 'עסק', default: true },
    { name: 'pricing', title: 'מע"מ והנחות' },
    { name: 'legal', title: 'ישות משפטית' },
  ],
  fields: [
    defineField({ name: 'businessName', title: 'שם העסק', type: 'string', group: 'business', validation: (r) => r.required().max(60) }),
    defineField({ name: 'tagline', title: 'משפט מפתח', type: 'string', group: 'business', validation: (r) => r.max(160) }),
    defineField({ name: 'logo', title: 'לוגו העסק (אופציונלי — ברירת המחדל היא הלוגו המובנה)', type: 'image', group: 'business' }),
    defineField({
      name: 'whatsappNumber',
      title: 'מספר וואטסאפ מרכזי (פורמט בינלאומי, ללא +)',
      description: '⚠️ דמו: 972500000000 — להחליף לפני עלייה לאוויר',
      type: 'string',
      group: 'business',
      validation: (r) => r.required().regex(/^972\d{8,9}$/, { name: 'international' }),
    }),
    defineField({ name: 'whatsappMessage', title: 'הודעה מוכנה בוואטסאפ', type: 'string', group: 'business', validation: (r) => r.max(200) }),
    defineField({ name: 'instagram', title: 'קישור לאינסטגרם', type: 'url', group: 'business' }),
    defineField({ name: 'linkedin', title: 'קישור ללינקדאין', type: 'url', group: 'business' }),
    defineField({
      name: 'vatRate',
      title: 'שיעור מע"מ',
      description: 'כשבר עשרוני: 0.18 = 18%',
      type: 'number',
      group: 'pricing',
      initialValue: 0.18,
      validation: (r) => r.required().min(0).max(0.5),
    }),
    defineField({
      name: 'autoDiscountMinHours',
      title: 'הנחה אוטומטית — מינימום שעות',
      type: 'number',
      group: 'pricing',
      initialValue: 4,
      validation: (r) => r.required().min(1).max(12),
    }),
    defineField({
      name: 'autoDiscountPercent',
      title: 'הנחה אוטומטית — אחוז',
      type: 'number',
      group: 'pricing',
      initialValue: 10,
      validation: (r) => r.required().integer().min(0).max(50),
    }),
    defineField({ name: 'legalCompanyName', title: 'שם החברה', type: 'string', group: 'legal', validation: (r) => r.required().max(120) }),
    defineField({ name: 'legalCompanyId', title: 'ח.פ', type: 'string', group: 'legal', validation: (r) => r.required().regex(/^\d{9}$/) }),
    defineField({ name: 'legalAddress', title: 'כתובת רשומה', type: 'string', group: 'legal', validation: (r) => r.required().max(160) }),
    defineField({ name: 'legalEmail', title: 'דוא"ל לפניות משפטיות', type: 'string', group: 'legal', validation: (r) => r.required().email() }),
    defineField({ name: 'accessibilityCoordinator', title: 'רכז/ת נגישות', type: 'string', group: 'legal', validation: (r) => r.required().max(80) }),
    defineField({ name: 'accessibilityPhone', title: 'טלפון רכז/ת נגישות', type: 'string', group: 'legal', validation: (r) => r.required().max(20) }),
    defineField({
      name: 'legalIsDemo',
      title: '⚠️ נתוני דמו — להחליף לפני עלייה לאוויר',
      description: 'כל עוד מסומן, באתר מוצג באנר אזהרה',
      type: 'boolean',
      group: 'legal',
      initialValue: true,
    }),
  ],
  preview: { prepare: () => ({ title: 'הגדרות אתר' }) },
});
