/** Third-party assets that require visible attribution (CC BY). Mirrors docs/asset-licenses.md. */
export type Credit = { title: string; author: string; authorUrl: string; source: string; license: string; licenseUrl: string; use: string };

const CC_BY_4 = { license: 'CC BY 4.0', licenseUrl: 'https://creativecommons.org/licenses/by/4.0/' };

export const CREDITS: Credit[] = [
  {
    title: 'New York City',
    author: 'golukumar',
    authorUrl: 'https://sketchfab.com/mortalityrexotable',
    source: 'https://sketchfab.com/3d-models/new-york-city-4737b6ee73ed4634ad5b414558fdfa45',
    ...CC_BY_4,
    use: 'בלוקי הרחובות והבניינים סביב המגדל בסיור התלת־ממדי, הבניין השכן ליד המגדל, והעצים ברחבה ולאורך השדרה (חלקים מהדגם, משוכפלים; דחוס לאתר, עם תאורת חלונות בלילה)',
  },
  {
    title: 'Minimalistic Modern Office',
    author: 'dylanheyes',
    authorUrl: 'https://sketchfab.com/dylanheyes',
    source: 'https://sketchfab.com/3d-models/minimalistic-modern-office-5540183da1c7452f810f8de33734879a',
    ...CC_BY_4,
    use: 'שולחן מנהלים, כיסא, שטיח ועציץ במשרדים הפרטיים (נלקחו רק הרהיטים, מפושטים ודחוסים)',
  },
  {
    title: 'free Loft 17 interior floors, view of the city.',
    author: 'dasy444',
    authorUrl: 'https://sketchfab.com/dasy444',
    source: 'https://sketchfab.com/3d-models/free-loft-17-interior-floors-view-of-the-city-1bc27584241b4078975b31dd4610d6e0',
    ...CC_BY_4,
    use: 'ספת העור, הכורסה, השולחן, השטיח והאגרטל בטרקלין של כל קומה (נלקחו רק הרהיטים), וחלל הדירות בבניין המגורים (חתוך ומפושט)',
  },
  {
    title: 'Artcollection room with Office',
    author: 'M.A',
    authorUrl: 'https://sketchfab.com/Jaideep.Malampati',
    source: 'https://sketchfab.com/3d-models/artcollection-room-with-office-96f53027ae2d41ba8031b29724ae8b7f',
    ...CC_BY_4,
    use: 'אולם הבריכה בלובי בניין המגורים (חתוך, מפושט ודחוס)',
  },
  {
    title: 'Meeting room',
    author: 'Titank',
    authorUrl: 'https://sketchfab.com/Titank_Crealis',
    source: 'https://sketchfab.com/3d-models/meeting-room-3fd65e8b05da4b9a94d287ae3f676fd1',
    ...CC_BY_4,
    use: 'שולחן הישיבות והכיסאות בחדרי הישיבות (נלקח רק השולחן עם הכיסאות, דחוס)',
  },
  {
    title: 'Road Signs',
    author: 'FrodoUndead',
    authorUrl: 'https://sketchfab.com/FrodoUndead',
    source: 'https://sketchfab.com/3d-models/road-signs-c39bf97110494b5db3de84165211f592',
    ...CC_BY_4,
    use: 'תמרורי מעבר חצייה, מהירות מותרת, רמזור לפניך ואיסור פנייה פרסה ברחובות',
  },
  {
    title: 'Fictional supercar - V12 Goblin',
    author: 'ollitei',
    authorUrl: 'https://sketchfab.com/ollitei',
    source: 'https://sketchfab.com/3d-models/fictional-supercar-v12-goblin-0a20e49ad5774d778567cb5c3f345786',
    ...CC_BY_4,
    use: 'מכונית הספורט הירוקה בתנועה ברחוב (דחוסה)',
  },
  {
    title: 'Lamborghini Revuelto',
    author: 'DRIVER-FIRE',
    authorUrl: 'https://sketchfab.com/DRIVER-FIRE',
    source: 'https://sketchfab.com/3d-models/lamborghini-revuelto-2c05874ee41f4060a061371ef096bb5b',
    ...CC_BY_4,
    use: 'המכונית הכתומה על הבמה בכניסה ובתנועה ברחוב (סמלי היצרן הוסרו, דחוסה). אין קשר ליצרן.',
  },
  {
    title: 'Office Plants pack LOWPOLY',
    author: 'EFX',
    authorUrl: 'https://sketchfab.com/evan4129',
    source: 'https://sketchfab.com/3d-models/office-plants-pack-lowpoly-7e55084ba28e49adaa8c22a817863475',
    ...CC_BY_4,
    use: 'עציצי הטופיארי בלובי, ליד הדלתות ועל האדניות ברחבה, וגדרות השיחים',
  },
  {
    title: 'Zsolnay Fountain',
    author: 'georgiyhazankin',
    authorUrl: 'https://sketchfab.com/georgiyhazankin',
    source: 'https://sketchfab.com/3d-models/zsolnay-fountain-a3d182f3e0fb44dcbec52a60eba591dc',
    ...CC_BY_4,
    use: 'המזרקה ברחבת הכניסה (דחוסה, המים מונפשים בקוד)',
  },
  {
    title: 'Reception',
    author: 'Arbin4444',
    authorUrl: 'https://sketchfab.com/digilife4444',
    source: 'https://sketchfab.com/3d-models/reception-757937555df54c9badcff1f836d3b385',
    ...CC_BY_4,
    use: 'דלפק השיש בקבלה בלובי (הדלפק בלבד)',
  },
  {
    title: 'Elevator with Animation LOWPOLY',
    author: 'EFX',
    authorUrl: 'https://sketchfab.com/evan4129',
    source: 'https://sketchfab.com/3d-models/elevator-with-animation-lowpoly-7c53a9a7db554e9da8dececfd3eac339',
    ...CC_BY_4,
    use: 'שתי המעליות בלובי: התא, הדלתות הנפתחות ולוחות הכפתורים (החזית בגוון ברונזה)',
  },
  {
    title: 'Reception',
    author: 'Arbin4444',
    authorUrl: 'https://sketchfab.com/digilife4444',
    source: 'https://sketchfab.com/3d-models/reception-25f7f98f09344d4abcbf20655715bc1c',
    ...CC_BY_4,
    use: 'שורות הספות ושולחנות הקפה לאורך קירות הלובי (הריהוט בלבד, מופשט)',
  },
];
